# Site settings
title: Beomseok's Personal Website
email: beomseok.jang@nhnent.com
description: beomseok's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: dktfr
permalink: /:year/:month/:day/:title/

#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: dktfrgithubio
disqus_url: "http://dktfr.github.io"
#########################################

# Build settings
markdown: kramdown
future:	true

# highlight

higilighter: true

Java:
  type: programming
  ace_mode: java
  color: "#b07219"
  extensions:
  - .java

# highlighter: pygments
# highlighter: rouge
# highlighter: false
